(()=>{
if(window.__needohAccountV3Loaded)return;
window.__needohAccountV3Loaded=true;
const SB='https://xawvgrktcqbtmcbpuizg.supabase.co';
const KEY='sb_publishable_PjR-iiuLbcoFqzjF8W-7Rg_S4X5cWwa';
const H={apikey:KEY,'Content-Type':'application/json'};
const SAVE_KEY='needohSquishWorldSaveV2';
const PLAYER_KEY='needohPlayerName';
const SESSION_KEY='needohAccountSessionV1';
const ACCOUNT_NAME_KEY='needohAccountNameV1';
const EXTRA_KEYS=['needohAdventureV4','needohAdventureV3','needohAdventureFinalV1','needohAdventureProgressFixV2'];
let authMode='login',authBusy=false,cloudBusy=false,cloudStatus='Not connected',cloudTimer=0,cloudStarted=false;
const $=id=>document.getElementById(id);
function readJson(k){try{const v=localStorage.getItem(k);return v?JSON.parse(v):null}catch(_){return null}}
function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function sessionToken(){return localStorage.getItem(SESSION_KEY)||''}
function accountName(){return String(localStorage.getItem(ACCOUNT_NAME_KEY)||'').trim()}
function localEnvelope(){const st=readJson(SAVE_KEY);if(!st)return null;const extras={};for(const k of EXTRA_KEYS){const v=readJson(k);if(v!==null)extras[k]=v}return{__needohCloudVersion:1,state:st,extras}}
function applyCloud(data,name){localStorage.setItem(PLAYER_KEY,name);if(!data){localStorage.removeItem(SAVE_KEY);for(const k of EXTRA_KEYS)localStorage.removeItem(k);return}if(data.__needohCloudVersion&&data.state&&typeof data.state==='object'){localStorage.setItem(SAVE_KEY,JSON.stringify(data.state));const ex=data.extras&&typeof data.extras==='object'?data.extras:{};for(const k of EXTRA_KEYS){if(Object.prototype.hasOwnProperty.call(ex,k)&&ex[k]!=null)localStorage.setItem(k,JSON.stringify(ex[k]));else localStorage.removeItem(k)}return}if(typeof data==='object')localStorage.setItem(SAVE_KEY,JSON.stringify(data))}
function storeSession(token,name){localStorage.setItem(SESSION_KEY,token);localStorage.setItem(ACCOUNT_NAME_KEY,name);localStorage.setItem(PLAYER_KEY,name)}
function clearSession(){localStorage.removeItem(SESSION_KEY);localStorage.removeItem(ACCOUNT_NAME_KEY)}
function clearGameLocal(){localStorage.removeItem(SAVE_KEY);localStorage.removeItem(PLAYER_KEY);for(const k of EXTRA_KEYS)localStorage.removeItem(k)}
async function rpc(name,body={},timeoutMs=5500){const c=new AbortController(),tm=setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(`${SB}/rest/v1/rpc/${name}`,{method:'POST',headers:H,body:JSON.stringify(body),signal:c.signal});const t=await r.text();if(!r.ok)throw new Error(t||`Account request failed (${r.status})`);return t?JSON.parse(t):null}finally{clearTimeout(tm)}}
function installStyle(){if($('accountV3Styles'))return;const s=document.createElement('style');s.id='accountV3Styles';s.textContent=`.av3-tabs{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:5px;background:#0004;border-radius:15px;margin:12px 0}.av3-tab{border:0;border-radius:11px;padding:10px;background:transparent;color:#c9c9da;font-weight:900;cursor:pointer}.av3-tab.on{background:linear-gradient(135deg,#21d8ae,#666cff);color:#fff}.av3-label{display:block;text-align:left;font-size:12px;color:#cac9db;font-weight:850;margin-top:9px}.av3-error{min-height:20px;color:#ff9bad;font-size:13px;font-weight:850;margin-top:8px}.av3-check{display:flex;gap:9px;text-align:left;align-items:flex-start;padding:10px;margin:10px 0;background:#ffd95e12;border:1px solid #ffd95e2d;border-radius:13px;color:#ffe99d;font-size:12px;line-height:1.35}.av3-note{color:#aaa8c2;font-size:11px;line-height:1.4;margin-top:10px}`;document.head.appendChild(s)}
function modalParts(){const modal=$('nameModal'),card=modal?.querySelector('.modal-card');return{modal,card}}
function hideAuth(){const {modal}=modalParts();modal?.classList.remove('show')}
function hasLocalProgress(){return !!readJson(SAVE_KEY)}
function errorText(code){if(code==='NAME_TAKEN')return'That player name already has an account. Use Log In or choose another name.';if(code==='NAME_INVALID')return'Use 2–20 characters: letters, numbers, spaces, _ or -.';if(code==='PASSWORD_INVALID')return'Password must be at least 8 characters.';if(code==='INVALID_LOGIN')return'Player name or password is incorrect.';if(code==='LOCKED')return'Too many incorrect attempts. Try again in about 10 minutes.';if(code==='SAVE_TOO_LARGE')return'Your current save is too large to import.';if(code==='OWNER_RESERVED')return'Attila is reserved for the owner account.';if(code==='OWNER_AUTH_REQUIRED')return'The Attila admin password is incorrect.';return'Could not connect to the account server.'}
function showAuth(message=''){
 installStyle();const {modal,card}=modalParts();if(!modal||!card){setTimeout(()=>showAuth(message),150);return}
 const old=(accountName()||localStorage.getItem(PLAYER_KEY)||'').slice(0,20);
 card.className='modal-card name-card';card.style.textAlign='center';
 card.innerHTML=`<div class="name-emoji">🫧</div><h2>Needoh Account</h2><p>Log in to restore your progress, or create a new account.</p><div class="av3-tabs"><button class="av3-tab ${authMode==='login'?'on':''}" id="av3LoginTab">LOG IN</button><button class="av3-tab ${authMode==='create'?'on':''}" id="av3CreateTab">CREATE ACCOUNT</button></div><label class="av3-label">PLAYER NAME</label><input id="av3Name" maxlength="20" autocomplete="username" value="${esc(old)}"><label class="av3-label">PASSWORD</label><input id="av3Pass" type="password" maxlength="128" autocomplete="${authMode==='create'?'new-password':'current-password'}" placeholder="At least 8 characters">${authMode==='create'?`<label class="av3-label">CONFIRM PASSWORD</label><input id="av3Confirm" type="password" maxlength="128" autocomplete="new-password" placeholder="Type password again"><div id="av3OwnerWrap"></div>${hasLocalProgress()?'<label class="av3-check"><input type="checkbox" id="av3Import" checked><span><b>Import progress already on this device</b><br>Your current coins, squishies and other progress will become this account’s starting save.</span></label>':''}`:''}<button class="btn primary" id="av3Submit" style="width:100%;margin-top:10px">${authMode==='create'?'CREATE ACCOUNT & PLAY':'LOG IN & PLAY'}</button><div class="av3-error" id="av3Error">${esc(message)}</div><div class="av3-note">The login box is part of the game itself. If the account server is temporarily unavailable, it will not reload or freeze the game.</div>`;
 modal.classList.add('show');
 $('av3LoginTab').onclick=()=>{if(!authBusy){authMode='login';showAuth()}};$('av3CreateTab').onclick=()=>{if(!authBusy){authMode='create';showAuth()}};
 const updateOwner=()=>{const w=$('av3OwnerWrap');if(!w)return;const own=String($('av3Name')?.value||'').trim().toLowerCase()==='attila';w.innerHTML=own?'<label class="av3-label">ATTILA ADMIN PASSWORD</label><input id="av3OwnerPass" type="password" maxlength="128" autocomplete="current-password" placeholder="Owner verification">':''};
 $('av3Name')?.addEventListener('input',updateOwner);updateOwner();$('av3Submit').onclick=submitAuth;
 for(const id of ['av3Name','av3Pass','av3Confirm'])$(id)?.addEventListener('keydown',e=>{if(e.key==='Enter')submitAuth()});
}
async function submitAuth(){if(authBusy)return;const name=String($('av3Name')?.value||'').replace(/\s+/g,' ').trim(),pass=String($('av3Pass')?.value||''),err=$('av3Error'),btn=$('av3Submit');if(name.length<2){if(err)err.textContent='Enter a player name with at least 2 characters.';return}if(pass.length<8){if(err)err.textContent='Password must be at least 8 characters.';return}if(authMode==='create'&&pass!==String($('av3Confirm')?.value||'')){if(err)err.textContent='The passwords do not match.';return}authBusy=true;if(btn){btn.disabled=true;btn.textContent='CONNECTING…'}if(err)err.textContent='';try{let r,useLocal=false;if(authMode==='create'){useLocal=!!$('av3Import')?.checked;const initial=useLocal?localEnvelope():null;if(name.toLowerCase()==='attila'){const owner=String($('av3OwnerPass')?.value||'');if(!owner){if(err)err.textContent='Enter the Attila admin password.';return}r=await rpc('needoh_account_create_owner',{p_player_name:name,p_password:pass,p_initial_save:initial,p_admin_password:owner})}else r=await rpc('needoh_account_create',{p_player_name:name,p_password:pass,p_initial_save:initial})}else r=await rpc('needoh_account_login',{p_player_name:name,p_password:pass});if(!r?.ok){if(err)err.textContent=errorText(r?.error);return}storeSession(r.session_token,r.player_name);if(!(authMode==='create'&&useLocal&&!r.save_data))applyCloud(r.save_data??null,r.player_name);else localStorage.setItem(PLAYER_KEY,r.player_name);sessionStorage.setItem('needohAccountJustLoggedInV3','1');location.reload()}catch(e){console.warn('Needoh account login failed',e);if(err)err.textContent='Could not connect. Your game was not changed. Try again.'}finally{authBusy=false;const b=$('av3Submit');if(b){b.disabled=false;b.textContent=authMode==='create'?'CREATE ACCOUNT & PLAY':'LOG IN & PLAY'}}}
async function cloudSave(manual=false){if(cloudBusy||!sessionToken())return false;let data=null;try{if(typeof save==='function')save(true);data=localEnvelope()}catch(_){}if(!data)return false;cloudBusy=true;try{const r=await rpc('needoh_account_save',{p_session_token:sessionToken(),p_save_data:data},5000);if(r?.ok){cloudStatus='Cloud saved';return true}if(r?.error==='SESSION_INVALID'){cloudStatus='Login expired — local save still works';if(manual)showAuth('Your login expired. Log in again to reconnect cloud saving.');return false}cloudStatus='Cloud save unavailable — local save still works';return false}catch(e){cloudStatus='Offline — local save still works';return false}finally{cloudBusy=false}}
function startCloud(){if(cloudStarted)return;cloudStarted=true;clearInterval(cloudTimer);setTimeout(()=>cloudSave(false),7000);cloudTimer=setInterval(()=>cloudSave(false),30000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')cloudSave(false)})}
function showAccountHub(){if(typeof openHub!=='function')return;const name=accountName()||localStorage.getItem(PLAYER_KEY)||'Player';openHub('☁️ Account',`<div class="notice"><b>Signed in as ${esc(name)}</b><br>${esc(cloudStatus)}</div><div class="card"><button class="btn primary" id="av3SaveNow">☁️ SAVE TO CLOUD</button> <button class="btn danger" id="av3Logout">🚪 LOG OUT</button></div>`);$('av3SaveNow').onclick=async()=>{const b=$('av3SaveNow');b.disabled=true;b.textContent='SAVING…';const ok=await cloudSave(true);b.disabled=false;b.textContent=ok?'✅ SAVED':'☁️ TRY AGAIN'};$('av3Logout').onclick=logout}
async function logout(){await cloudSave(false);const tok=sessionToken();try{if(tok)await rpc('needoh_account_logout',{p_session_token:tok},3500)}catch(_){}clearSession();clearGameLocal();try{sessionStorage.removeItem('needohAttilaAdminUnlockedV1')}catch(_){}location.reload()}
function fixAccountButton(){const b=$('changeNameBtn');if(!b)return;b.textContent='☁️ Account';b.title='Cloud account and logout';b.onclick=showAccountHub}
async function boot(){installStyle();fixAccountButton();setInterval(fixAccountButton,2000);const tok=sessionToken(),nm=accountName();if(!tok){showAuth();return}if(nm)localStorage.setItem(PLAYER_KEY,nm);hideAuth();cloudStatus='Checking account…';try{const r=await rpc('needoh_account_resume',{p_session_token:tok},5000);if(r?.ok){storeSession(tok,r.player_name||nm||'Player');cloudStatus='Connected · progress saves automatically';hideAuth();startCloud();return}clearSession();cloudStatus='Login required';showAuth('Your saved login expired. Log in again to continue.')}catch(e){console.warn('Needoh account resume offline',e);cloudStatus='Offline · using local progress';hideAuth();startCloud();try{toast('☁️ Account server unavailable — playing from local save')}catch(_){} }}
boot();
})();
