(()=>{
if(window.__needohAdv4Loaded)return;
const KEY='needohAdventureV4';
const $id=id=>document.getElementById(id),clS=n=>Math.max(1,Math.min(30,Math.floor(Number(n)||1))),clC=n=>Math.max(0,Math.min(30,Math.floor(Number(n)||0)));
function sx(){state.seasonX=state.seasonX&&typeof state.seasonX==='object'?state.seasonX:{};const s=state.seasonX;s.adventure=s.adventure&&typeof s.adventure==='object'?s.adventure:{stage:1,cleared:0,hp:0};s.keys={bronze:0,crystal:0,cosmic:0,void:0,...(s.keys||{})};s.enchantShards=Number(s.enchantShards)||0;s.pass=s.pass&&typeof s.pass==='object'?s.pass:{};s.pass.xp=Number(s.pass.xp)||0;return s}
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&typeof x==='object'?x:null}catch(_){return null}}
function write(p){const q={stage:clS(p.stage),cleared:clC(p.cleared),hp:Math.max(0,Number(p.hp)||0)};try{localStorage.setItem(KEY,JSON.stringify(q))}catch(_){}const a=sx().adventure;a.stage=q.stage;a.cleared=q.cleared;a.hp=q.hp;return q}
function progress(){let p=read();if(!p){const a=sx().adventure;p={stage:clS(a.stage),cleared:clC(a.cleared),hp:Math.max(0,Number(a.hp)||0)};for(const k of ['needohAdventureV3','needohAdventureFinalV1','needohAdventureProgressFixV2']){try{const x=JSON.parse(localStorage.getItem(k)||'null');if(x){p.stage=Math.max(p.stage,clS(x.stage));p.cleared=Math.max(p.cleared,clC(x.cleared))}}catch(_){}}if(p.cleared<30&&p.stage<=p.cleared)p.stage=p.cleared+1;if(p.cleared>=30){p.stage=30;p.hp=0}}return write(p)}
const maxHp=s=>Math.round(220+s*s*42+(s%5===0?s*180:0));
function enemy(s){const zone=s<=10?'Meadow Rift':s<=20?'Crystal Abyss':'Void Citadel',bosses={5:'Goo Guardian',10:'Crystal Hydra',15:'Rift Warden',20:'Void Dragon',25:'Reality Breaker',30:'Final Architect'};return{zone,boss:s%5===0,name:bosses[s]||`Rift Creature ${s}`}}
function power(){let m=1;try{m=Math.max(1,Number(rarity(state.selected)?.mult)||1)}catch(_){}const p=Math.max(0,Number(state.mega?.prestige?.count)||0),base=Math.max(1,(Number(state.clickPower)||1)*(Number(state.baseMult)||1)*m);return Math.max(25,Math.round(35+Math.log10(base+10)*18+p*12))}
function rewardCoins(s){let per=1;try{per=Math.max(1,(Number(state.clickPower)||1)*(Number(state.baseMult)||1)*(Number(rarity(state.selected)?.mult)||1))}catch(_){}return Math.max(10000*s*s,per*s*18)}
function grant(s){const x=sx(),coins=rewardCoins(s);try{addCoins(coins)}catch(_){state.coins=(Number(state.coins)||0)+coins}x.pass.xp=(Number(x.pass.xp)||0)+150;x.enchantShards+=s%5===0?5:1;if(s%3===0)x.keys.bronze++;if(s%5===0)x.keys.crystal++;if(s%10===0)x.keys.cosmic++;if(s===30)x.keys.void++;for(const [n,name] of [[10,'Adventure Blob'],[20,'Rift Knight'],[30,'Void Emperor']])if(s===n&&!state.owned.includes(name)){state.owned.push(name);state.selected=name}return coins}
function attack(){let p=progress(),s=clS(p.stage);if(p.cleared>=30)return show();if(!p.hp)p.hp=maxHp(s);p.hp=Math.max(0,p.hp-power());if(p.hp<=0){const next=s<30?s+1:30,cleared=Math.max(p.cleared,s);p=write({stage:next,cleared,hp:s<30?maxHp(next):0});try{save(true)}catch(_){}const coins=grant(s);write(p);try{save(true);render()}catch(_){}try{toast(s<30?`🗺️ Stage ${s} cleared! Stage ${next} unlocked! +${fmt(coins)} coins`:'🏆 Adventure complete!')}catch(_){}}else{write(p);try{save(true);render()}catch(_){}}show()}
function select(n){let p=progress();n=clS(n);if(n>Math.min(30,p.cleared+1))return;write({stage:n,cleared:p.cleared,hp:maxHp(n)});try{save(true)}catch(_){}show()}
function show(){let p=progress(),s=clS(p.stage);if(p.cleared<30&&!p.hp)p=write({...p,hp:maxHp(s)});const e=enemy(s),max=maxHp(s),done=p.cleared>=30,pct=done?0:Math.max(0,Math.min(100,p.hp/max*100));const map=Array.from({length:30},(_,i)=>i+1).map(n=>{const en=enemy(n),locked=n>Math.min(30,p.cleared+1),cleared=n<=p.cleared,current=n===s&&!locked;return`<button class="sx-stage ${locked?'locked':''} ${en.boss?'boss':''}" data-adv4="${n}" ${locked?'disabled':''}><b>${en.boss?'👹':'🫧'} ${n}</b><span class="small">${cleared?'✅':current?'⚔️':''}</span></button>`}).join('');openHub('🗺️ Adventure Mode',`<div id="adv4Root"><div class="notice"><b>Adventure Engine v4</b> · ${p.cleared}/30 cleared. Progress is stored separately so older code cannot push you back to Stage 1.</div><div class="sx-card" style="text-align:center"><h2>${done?'🏆 Adventure Complete':`${e.boss?'👹':'🫧'} ${escapeHtml(e.name)}`}</h2><div class="sx-tag">${e.zone} · Stage ${s}</div>${done?'<p>All 30 stages cleared.</p>':`<div class="sx-meter" style="margin:12px 0"><div style="width:${pct}%"></div></div><b>${fmt(p.hp)} / ${fmt(max)} HP</b><div class="small">Your hit: ~${fmt(power())}</div><button class="btn danger" id="adv4Attack">⚔️ ATTACK</button>`}</div><h3>Adventure Map</h3><div class="sx-map">${map}</div></div>`);if($id('adv4Attack'))$id('adv4Attack').onclick=attack;document.querySelectorAll('[data-adv4]').forEach(b=>b.onclick=()=>select(Number(b.dataset.adv4)))}
function addBtn(){const bar=document.querySelector('.featurebar');if(bar&&!$id('adv4Btn')){const b=document.createElement('button');b.id='adv4Btn';b.className='btn';b.textContent='🗺️ Adventure';b.onclick=show;bar.insertBefore(b,$id('adminBtn')||null)}}
function hijack(){addBtn();progress();if(window.__needohSeasonAdventure)window.__needohSeasonAdventure.adventure=show;const title=String($id('hubTitle')?.textContent||'');if(title==='🗺️ Adventure Mode'&&!$id('adv4Root'))queueMicrotask(show)}
document.addEventListener('click',e=>{const b=e.target?.closest?.('[data-sx-open="Adventure Mode"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();show()},true);
new MutationObserver(hijack).observe(document.body,{childList:true,subtree:true});addBtn();hijack();setInterval(hijack,500);window.__needohAdventureV4={show,attack,progress};window.__needohAdv4Loaded=true;
})();