(()=>{
if(window.__needohBugReportLoaded)return;
window.__needohBugReportLoaded=true;
const SB='https://xawvgrktcqbtmcbpuizg.supabase.co';
const KEY='sb_publishable_PjR-iiuLbcoFqzjF8W-7Rg_S4X5cWwa';
const H={apikey:KEY,'Content-Type':'application/json'};
const SESSION='needohAccountSessionV1',ACCOUNT='needohAccountNameV1',$=id=>document.getElementById(id);
function token(){return localStorage.getItem(SESSION)||''}
function owner(){try{return String(localStorage.getItem(ACCOUNT)||'').toLowerCase()==='attila'&&window.__needohIsOwnerAdmin?.()===true}catch(_){return false}}
function sx(){state.socialX=state.socialX&&typeof state.socialX==='object'?state.socialX:{};if(state.socialX.bugFinderUnlocked==null)state.socialX.bugFinderUnlocked=false;if(state.socialX.bugFinderEquipped==null)state.socialX.bugFinderEquipped=false;return state.socialX}
function esc(s){try{return escapeHtml(String(s??''))}catch(_){return String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]))}}
async function rpc(name,body={},timeout=6500){const c=new AbortController(),tm=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(`${SB}/rest/v1/rpc/${name}`,{method:'POST',headers:H,body:JSON.stringify(body),signal:c.signal}),t=await r.text();if(!r.ok)throw new Error(t||name);return t?JSON.parse(t):null}finally{clearTimeout(tm)}}
function saveNow(){try{save(true);render()}catch(_){}}
function css(){if($('bugFinderStyles'))return;const s=document.createElement('style');s.id='bugFinderStyles';s.textContent=`#stage.bug-finder-stage{position:relative;overflow:hidden;border-radius:20px;isolation:isolate;background:linear-gradient(180deg,#020805,#06130b)!important;box-shadow:inset 0 0 70px #00ff5533,0 0 32px #00ff5530}#stage.bug-finder-stage>*:not(.bug-finder-rain){z-index:2}.bug-finder-rain{position:absolute!important;inset:0;z-index:0!important;overflow:hidden;pointer-events:none;background:radial-gradient(circle at 50% 45%,#00ff3715,transparent 50%),repeating-linear-gradient(90deg,#00ff0804 0 1px,transparent 1px 34px)}.bug-finder-col{position:absolute;top:-160%;width:30px;color:#70ff8e;font:900 15px/18px ui-monospace,SFMono-Regular,Menlo,monospace;text-shadow:0 0 7px #00ff55;white-space:pre;opacity:.7;animation:bugRain linear infinite}#stage.bug-finder-stage .needoh{filter:drop-shadow(0 0 15px #00ff62) saturate(1.25)}#stage.bug-finder-stage .rarity-label{color:#8dffab;text-shadow:0 0 10px #00ff62}#stage.bug-finder-stage .floating{position:absolute!important;z-index:20!important;color:#fff!important;text-shadow:0 2px 5px #000,0 0 12px #00ff62!important}@keyframes bugRain{from{transform:translateY(-15%)}to{transform:translateY(260%)}}.bug-badge{display:inline-flex;gap:6px;align-items:center;padding:5px 9px;border-radius:999px;background:#00ff5413;border:1px solid #00ff5555;color:#8dffab;font-weight:900;font-size:11px}.bug-card{background:#07110bcc;border:1px solid #00ff5535;border-radius:16px;padding:12px;margin:8px 0}`;document.head.appendChild(s)}
function rain(){css();const stage=$('stage');if(!stage)return;const on=!!sx().bugFinderUnlocked&&!!sx().bugFinderEquipped;stage.classList.toggle('bug-finder-stage',on);let r=$('bugFinderRain');if(!on){r?.remove();return}if(r)return;r=document.createElement('div');r.id='bugFinderRain';r.className='bug-finder-rain';const chars='010101アイウエオカキクケコ<>[]{}$#@ZXCV';for(let i=0;i<24;i++){const c=document.createElement('span');c.className='bug-finder-col';c.style.left=`${(i*4.3)%100}%`;c.style.animationDuration=`${3.4+(i%7)*.55}s`;c.style.animationDelay=`-${(i%9)*.7}s`;let txt='';for(let j=0;j<34;j++)txt+=chars[(i*13+j*7)%chars.length]+'\n';c.textContent=txt;r.appendChild(c)}stage.prepend(r)}
function equip(v){const s=sx();if(!s.bugFinderUnlocked)return;s.bugFinderEquipped=!!v;saveNow();rain();try{toast(v?'🐞 Bug Finder equipped':'Bug Finder unequipped')}catch(_){}show()}
function fields(){return `<div class="bug-card"><label class="small">Category</label><select class="field" id="bugCategory"><option value="gameplay">Gameplay</option><option value="account">Account / Password</option><option value="auction">Auctions</option><option value="soccer">Soccer</option><option value="worlds">Worlds / Balance</option><option value="multiplayer">Multiplayer</option><option value="visual">Visual</option><option value="other">Other</option></select><label class="small">Short title</label><input class="field" id="bugTitle" maxlength="80" placeholder="What is broken?"><label class="small">What happened?</label><textarea class="field" id="bugDescription" maxlength="2000" rows="5" placeholder="Tell us what you expected and what actually happened."></textarea><label class="small">Steps to reproduce</label><textarea class="field" id="bugSteps" maxlength="2000" rows="4" placeholder="1. Open... 2. Click... 3. Bug happens..."></textarea><button class="btn gold" id="bugSubmit">🐞 SUBMIT BUG</button></div>`}
function cosmeticCard(){const s=sx();return `<div class="bug-card"><div class="bug-badge">🐞 BUG FINDER COSMETIC</div><h3>Matrix Rain Hacker Background</h3><p class="small">${s.bugFinderUnlocked?'Unlocked permanently for this account.':'Submit your first real bug report to unlock it.'}</p>${s.bugFinderUnlocked?`<button class="btn ${s.bugFinderEquipped?'danger':'gold'}" id="bugEquip">${s.bugFinderEquipped?'UNEQUIP':'EQUIP BUG FINDER'}</button>`:''}</div>`}
function show(){css();if(typeof openHub!=='function')return;const logged=!!token();openHub('🐞 Report a Bug',`${cosmeticCard()}${logged?fields():'<div class="notice">Log in to your Needoh account first so the report and cosmetic reward can be attached to your account.</div>'}${owner()?'<button class="btn admin" id="bugViewReports">👑 VIEW PLAYER BUG REPORTS</button>':''}`);if($('bugEquip'))$('bugEquip').onclick=()=>equip(!sx().bugFinderEquipped);if($('bugSubmit'))$('bugSubmit').onclick=submit;if($('bugViewReports'))$('bugViewReports').onclick=viewReports}
async function submit(){const b=$('bugSubmit');if(!b||b.disabled)return;const title=String($('bugTitle')?.value||'').trim(),desc=String($('bugDescription')?.value||'').trim(),steps=String($('bugSteps')?.value||'').trim();if(title.length<5)return toast('Bug title needs at least 5 characters');if(desc.length<10)return toast('Please describe the bug in a little more detail');b.disabled=true;b.textContent='SENDING…';try{const r=await rpc('needoh_bug_report',{p_session_token:token(),p_category:$('bugCategory')?.value||'other',p_title:title,p_description:desc,p_steps:steps});if(!r?.ok){if(r?.error==='RATE_LIMIT')return toast('Too many reports right now — try again later');if(r?.error==='SESSION_INVALID')return toast('Log in again before reporting');return toast('Could not submit bug')}const s=sx();s.bugFinderUnlocked=true;if(r.first_reward||!s.bugFinderEquipped)s.bugFinderEquipped=true;saveNow();rain();toast(r.first_reward?'🐞 Bug submitted — BUG FINDER UNLOCKED!':'🐞 Bug report submitted — thank you!');show()}catch(e){console.warn('Bug report failed',e);toast('Could not submit bug right now')}finally{const x=$('bugSubmit');if(x){x.disabled=false;x.textContent='🐞 SUBMIT BUG'}}}
async function syncStatus(){if(!token())return;try{const r=await rpc('needoh_bug_status',{p_session_token:token()},5000);if(r?.ok&&r.bug_finder_unlocked&&!sx().bugFinderUnlocked){sx().bugFinderUnlocked=true;saveNow();rain()}}catch(_){}}
async function viewReports(){try{const r=await rpc('needoh_bug_list',{p_session_token:token()},6500);if(!r?.ok)return toast('Could not load reports');const rows=Array.isArray(r.reports)?r.reports:[];openHub('👑 Player Bug Reports',rows.map(x=>`<div class="bug-card"><div class="small">${esc(x.category)} · ${new Date(x.created_at).toLocaleString()} · ${esc(x.player_name)}</div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p>${x.steps?`<div class="notice"><b>Steps:</b><br>${esc(x.steps)}</div>`:''}<span class="bug-badge">${esc(x.status)}</span></div>`).join('')||'<div class="notice">No bug reports yet.</div>')}catch(e){toast('Could not load reports')}}
function button(){const bar=document.querySelector('.featurebar');if(!bar)return;let b=$('bugReportBtn');if(!b){b=document.createElement('button');b.id='bugReportBtn';b.className='btn';b.textContent='🐞 Report a Bug';b.onclick=show;bar.insertBefore(b,$('adminBtn')||null)}}
css();button();rain();syncStatus();setInterval(()=>{button();const stage=$('stage'),should=!!sx().bugFinderUnlocked&&!!sx().bugFinderEquipped,has=!!$('bugFinderRain');if(stage&&(stage.classList.contains('bug-finder-stage')!==should||has!==should))rain()},3000);window.__needohBugReport={show,equip};
})();
