(() => {
  const SB_URL='https://xawvgrktcqbtmcbpuizg.supabase.co';
  const SB_KEY='sb_publishable_PjR-iiuLbcoFqzjF8W-7Rg_S4X5cWwa';
  const headers={apikey:SB_KEY,'Content-Type':'application/json'};
  const pkey=(name=playerName())=>cleanPlayerName(name).toLowerCase();
  const active={luck_rush:null,boss_damage:null,box_frenzy:null,secret_rush:null};
  const meta={luck_rush:['🍀','Luck Rush'],boss_damage:['⚔️','Boss Damage'],box_frenzy:['🎁','Box Frenzy'],secret_rush:['✨','Secret Squishy Rush']};
  let checking=false,seasonPending=0,lastEventText='';
  async function api(path,opts={}){const r=await fetch(`${SB_URL}/rest/v1/${path}`,{...opts,headers:{...headers,...(opts.headers||{})}});if(!r.ok)throw new Error((await r.text())||`Online error ${r.status}`);if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
  const mult=t=>{const r=active[t];return r&&Date.parse(r.ends_at)>Date.now()?Math.max(1,Number(r.multiplier)||1):1};
  const isActive=t=>mult(t)>1;
  function ensureUi(){
    if(!document.getElementById('eventRewardStyles')){const s=document.createElement('style');s.id='eventRewardStyles';s.textContent=`#extraEventBanner{position:fixed;top:82px;left:50%;transform:translateX(-50%) translateY(-12px);z-index:95;opacity:0;pointer-events:none;max-width:calc(100vw - 24px);padding:10px 16px;border-radius:16px;background:linear-gradient(135deg,#694cff,#00d9c0,#ffb13b);font-weight:1000;text-align:center;box-shadow:0 10px 40px rgba(75,60,255,.4);transition:.2s}#extraEventBanner.show{opacity:1;transform:translateX(-50%) translateY(0)}.daily-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:7px}.daily-day{padding:10px 7px;border-radius:14px;background:rgba(255,255,255,.07);text-align:center;border:1px solid rgba(255,255,255,.08)}.daily-day.current{outline:2px solid #ffd95e;background:rgba(255,217,94,.12)}.season-podium{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:12px}.season-podium .card{text-align:center}@media(max-width:720px){.daily-grid{grid-template-columns:repeat(2,1fr)}.season-podium{grid-template-columns:1fr}}`;document.head.appendChild(s)}
    if(!document.getElementById('extraEventBanner')){const b=document.createElement('div');b.id='extraEventBanner';document.body.appendChild(b)}
  }
  async function checkEvents(){if(checking)return;checking=true;try{const rows=await api('needoh_events?select=id,event_type,multiplier,starts_at,ends_at,created_at&event_type=in.(luck_rush,boss_damage,box_frenzy,secret_rush)&order=created_at.desc&limit=30'),n=Date.now();for(const t of Object.keys(active))active[t]=(rows||[]).find(r=>r.event_type===t&&Date.parse(r.starts_at)<=n&&Date.parse(r.ends_at)>n)||null;updateBanner()}catch(e){console.warn('Event check failed',e)}finally{checking=false}}
  function updateBanner(){ensureUi();const parts=Object.keys(active).filter(isActive).map(t=>`${meta[t][0]} ${Number(mult(t)).toLocaleString()}× ${meta[t][1]}`),b=$('extraEventBanner');if(parts.length){b.textContent=`🔥 LIVE EVENT: ${parts.join(' · ')}`;b.classList.add('show');const text=parts.join('|');if(text!==lastEventText){lastEventText=text;toast('🔥 A global event is active!')}}else{b.classList.remove('show');lastEventText=''}}
  async function startEvent(type,multiplier=5,minutes=5){if(!meta[type])throw new Error('Unknown event');const start=new Date(),end=new Date(start.getTime()+Math.max(1,Math.min(30,minutes))*60000);await api('needoh_events',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify([{event_type:type,multiplier:Math.max(2,Number(multiplier)||2),starts_at:start.toISOString(),ends_at:end.toISOString(),created_by:'Attila'}])});await checkEvents()}
  window.__needohEvents={active:isActive,mult,start:startEvent,meta};

  const baseAddCoins=addCoins;
  addCoins=function(amount){const before=Math.max(0,Number(state.coins)||0),r=baseAddCoins(amount),gain=Math.max(0,(Number(state.coins)||0)-before);if(gain>0&&Number.isFinite(gain))seasonPending+=Math.min(gain,1e100);return r};
  function seasonInfo(offset=0){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7)+offset*7);const start=new Date(d),end=new Date(d);end.setDate(end.getDate()+7);return{key:`season-${start.getFullYear()}-${String(start.getMonth()+1).padStart(2,'0')}-${String(start.getDate()).padStart(2,'0')}`,start,end}}
  async function flushSeason(){if(seasonPending<=0||playerName()==='Player')return;const amount=seasonPending;seasonPending=0;try{await api('rpc/needoh_add_season_score',{method:'POST',body:JSON.stringify({p_season_key:seasonInfo().key,p_player_key:pkey(),p_player_name:playerName(),p_amount:amount})})}catch(e){seasonPending+=amount}}

  const DAILY=[{icon:'🪙',label:'10K',coins:1e4},{icon:'🪙',label:'50K',coins:5e4},{icon:'🎁',label:'250K',coins:2.5e5},{icon:'🪙',label:'1M',coins:1e6},{icon:'💎',label:'5M',coins:5e6},{icon:'🌟',label:'25M',coins:2.5e7},{icon:'🌈',label:'Rainbow',item:'Rainbow'}];
  const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const shift=(s,n)=>{const d=new Date(`${s}T12:00:00`);d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  async function showDaily(){openHub('🎁 Daily Rewards','<div class="card">Loading your streak…</div>');try{const rows=await api(`needoh_daily_claims?select=player_key,last_claim_date,streak,total_claims&player_key=eq.${encodeURIComponent(pkey())}&limit=1`),row=rows?.[0],td=today(),last=row?.last_claim_date||'',claimed=last===td;let streak=Number(row?.streak)||0;if(last&&last!==td&&last!==shift(td,-1))streak=0;const day=claimed?((Math.max(1,streak)-1)%7)+1:(streak%7)+1;const cards=DAILY.map((r,i)=>`<div class="daily-day ${i+1===day?'current':''}"><b>Day ${i+1}</b><div style="font-size:28px">${r.icon}</div><small>${r.label}</small></div>`).join('');openHub('🎁 Daily Rewards',`<div class="notice">Claim every day. Day 7 gives the exclusive 🌈 Rainbow squishy.</div><div class="daily-grid">${cards}</div><div class="card" style="margin-top:12px;text-align:center"><h3>${claimed?'✅ Today claimed':`🔥 Current streak: ${streak} days`}</h3><button class="btn gold" id="claimDailyBtn" ${claimed?'disabled':''}>${claimed?'COME BACK TOMORROW':'🎁 CLAIM DAY '+day}</button></div>`);if(!claimed)$('claimDailyBtn').onclick=()=>claimDaily(row,streak,day)}catch(e){openHub('🎁 Daily Rewards','<div class="notice">Daily rewards could not connect.</div>')}}
  async function claimDaily(row,streak,day){const reward=DAILY[day-1],body={player_key:pkey(),player_name:playerName(),last_claim_date:today(),streak:streak+1,total_claims:(Number(row?.total_claims)||0)+1,updated_at:new Date().toISOString()};try{await api('needoh_daily_claims?on_conflict=player_key',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify([body])});if(reward.coins)addCoins(reward.coins);if(reward.item&&!state.owned.includes(reward.item)){state.owned.push(reward.item);state.selected=reward.item}save(true);render();toast(reward.item?`🌈 ${reward.item} unlocked!`:`🎁 +${fmt(reward.coins)} coins`);showDaily()}catch(e){toast('Could not claim daily reward')}}

  async function showSeason(){openHub('🏆 Weekly Season','<div class="card">Loading season…</div>');try{await flushSeason();const cur=seasonInfo(),prev=seasonInfo(-1),rows=await api(`needoh_season_scores?select=player_key,player_name,score&season_key=eq.${encodeURIComponent(cur.key)}&order=score.desc&limit=25`),prevTop=await api(`needoh_season_scores?select=player_key,player_name,score&season_key=eq.${encodeURIComponent(prev.key)}&order=score.desc&limit=3`),pod=(rows||[]).slice(0,3).map((x,i)=>`<div class="card"><div style="font-size:32px">${['🥇','🥈','🥉'][i]}</div><b>${escapeHtml(x.player_name)}</b><div class="reward">${fmt(Number(x.score)||0)}</div></div>`).join(''),lines=(rows||[]).map((x,i)=>`<div class="leader-row"><b>#${i+1}</b><div><b>${escapeHtml(x.player_name)}</b><div class="small">Weekly coins earned</div></div><div class="reward">${fmt(Number(x.score)||0)}</div></div>`).join('');const idx=(prevTop||[]).findIndex(x=>x.player_key===pkey()),rewards=['Diamond','Thunder','Rainbow'];let claim='';if(idx>=0){const c=await api(`needoh_season_claims?select=player_key&season_key=eq.${encodeURIComponent(prev.key)}&player_key=eq.${encodeURIComponent(pkey())}&limit=1`);if(!c?.length)claim=`<div class="notice">🎉 Last season: #${idx+1}! <button class="btn gold" id="claimSeasonPrize">Claim ${rewards[idx]}</button></div>`}const secs=Math.max(0,Math.floor((cur.end-Date.now())/1000));openHub('🏆 Weekly Season',`${claim}<div class="notice">Resets every Monday · ${Math.floor(secs/86400)}d ${Math.floor((secs%86400)/3600)}h left · Top 3 earn exclusive squishies.</div><div class="season-podium">${pod||'<div class="card">No scores yet.</div>'}</div>${lines}`);if($('claimSeasonPrize'))$('claimSeasonPrize').onclick=()=>claimSeason(prev.key,idx+1,rewards[idx])}catch(e){openHub('🏆 Weekly Season','<div class="notice">Season leaderboard could not connect.</div>')}}
  async function claimSeason(key,rank,item){try{await api('needoh_season_claims',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify([{season_key:key,player_key:pkey(),player_name:playerName(),rank,reward_item:item}])});if(!state.owned.includes(item))state.owned.push(item);state.selected=item;state.seasonTitles=Array.isArray(state.seasonTitles)?state.seasonTitles:[];const title=rank===1?'Season Champion':rank===2?'Season Runner-Up':'Season Top 3';if(!state.seasonTitles.includes(title))state.seasonTitles.push(title);save(true);render();toast(`🏆 ${item} unlocked!`);showSeason()}catch(e){toast('Reward already claimed')}}

  const baseSquish=squish;
  squish=function(ev){const before=state.squishes;baseSquish(ev);if(isActive('secret_rush')&&state.squishes>before){const chance=Math.min(.08,.002*mult('secret_rush'));if(Math.random()<chance){const list=window.__needohLimitedRarities||[],r=list[Math.floor(Math.random()*list.length)];if(r&&!state.owned.includes(r.name)){state.owned.push(r.name);state.selected=r.name;save(true);render();toast(`✨ SECRET DROP: ${r.icon} ${r.name}!`)}}}};

  function addFeature(id,label,fn){if($(id))return;const b=document.createElement('button');b.id=id;b.className='btn';b.textContent=label;b.onclick=fn;document.querySelector('.featurebar')?.insertBefore(b,$('adminBtn'))}
  addFeature('dailyBtn','🎁 Daily',showDaily);addFeature('seasonBtn','🏆 Season',showSeason);
  ensureUi();checkEvents();flushSeason();setInterval(checkEvents,2000);setInterval(updateBanner,500);setInterval(flushSeason,5000);
  window.__needohEventRewardsLoaded=true;
})();