(() => {
  const SB_URL='https://xawvgrktcqbtmcbpuizg.supabase.co';
  const SB_KEY='sb_publishable_PjR-iiuLbcoFqzjF8W-7Rg_S4X5cWwa';
  const headers={apikey:SB_KEY,'Content-Type':'application/json'};
  const pkey=(name=playerName())=>cleanPlayerName(name).toLowerCase();
  const ownerAdmin=()=>pkey()==='attila';
  let sending=false,lastSend=0;
  async function api(path,opts={}){const r=await fetch(`${SB_URL}/rest/v1/${path}`,{...opts,headers:{...headers,...(opts.headers||{})}});if(!r.ok)throw new Error((await r.text())||`Online error ${r.status}`);if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
  function styles(){if(document.getElementById('socialAdminStyles'))return;const s=document.createElement('style');s.id='socialAdminStyles';s.textContent=`.chat-badge{display:inline-block;padding:2px 7px;border-radius:999px;font-size:10px;font-weight:1000}.chat-badge.owner{background:#ffd95e;color:#2d2200}.chat-badge.temp{background:#b58cff;color:#170b31}.chat-meta{display:flex;gap:7px;align-items:center;flex-wrap:wrap;font-size:11px;color:#aaa8c2;margin-bottom:6px}.chat-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.chat-actions .btn{font-size:11px;padding:6px 8px}.control-center{border:1px solid rgba(124,247,212,.35)!important;background:linear-gradient(135deg,rgba(124,247,212,.09),rgba(111,88,255,.1))!important}.control-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:10px 0}.control-kpi{padding:10px;border-radius:14px;background:rgba(0,0,0,.18);text-align:center}.control-kpi b{display:block;font-size:21px}@media(max-width:720px){.control-kpis{grid-template-columns:1fr 1fr}}`;document.head.appendChild(s)}
  async function myMute(){const rows=await api(`needoh_chat_mutes?select=muted_until,reason&target_key=eq.${encodeURIComponent(pkey())}&limit=1`),m=rows?.[0];return m&&Date.parse(m.muted_until)>Date.now()?m:null}
  showMessages=async function(){
    openHub('💬 Global Chat','<div class="card">Loading chat…</div>');
    try{
      const [rows,mute]=await Promise.all([api('needoh_messages?select=id,author,author_key,badge,body,created_at&order=created_at.desc&limit=100'),myMute()]);
      const cards=(rows||[]).map(m=>{const badge=m.badge==='OWNER'?'<span class="chat-badge owner">OWNER</span>':m.badge==='TEMP ADMIN'?'<span class="chat-badge temp">TEMP ADMIN</span>':'';const actions=isAdmin()?`<div class="chat-actions"><button class="btn danger" data-chat-delete="${escapeHtml(m.id)}">Delete</button>${ownerAdmin()&&m.author_key&&m.author_key!=='attila'&&m.author_key!=='system'?`<button class="btn" data-chat-mute="${escapeHtml(m.author_key)}" data-chat-name="${escapeHtml(m.author)}">Mute 10m</button>`:''}</div>`:'';return `<div class="message-card"><div class="chat-meta"><b>${m.author_key==='system'?'📢':'👤'} ${escapeHtml(m.author)}</b>${badge}<span>${new Date(m.created_at).toLocaleString()}</span></div><div class="message-text">${escapeHtml(m.body)}</div>${actions}</div>`}).join('');
      const muted=mute?`<div class="notice">🔇 You are muted until ${new Date(mute.muted_until).toLocaleTimeString()}. ${escapeHtml(mute.reason||'')}</div>`:'';
      openHub('💬 Global Chat',`${muted}<div class="notice">Live chat across all devices · 5-second anti-spam cooldown.</div><div class="message-form" style="grid-template-columns:1fr auto"><textarea class="field" id="messageText" maxlength="300" placeholder="Type a message..." ${mute?'disabled':''}></textarea><button class="btn primary" id="sendMessageBtn" ${mute?'disabled':''}>Send</button></div><div class="messages-list">${cards||'<div class="card">No messages yet.</div>'}</div>`);
      if(!mute)$('sendMessageBtn').onclick=sendMessage;
      document.querySelectorAll('[data-chat-delete]').forEach(b=>b.onclick=()=>deleteMessageOnline(b.dataset.chatDelete));
      document.querySelectorAll('[data-chat-mute]').forEach(b=>b.onclick=()=>mutePlayer(b.dataset.chatMute,b.dataset.chatName,10));
    }catch(e){openHub('💬 Global Chat','<div class="notice">Chat could not connect.</div>')}
  };
  sendMessage=async function(){if(sending)return;const text=String($('messageText')?.value||'').trim().slice(0,300);if(!text)return;if(Date.now()-lastSend<5000)return toast('⏳ Wait 5 seconds between messages');sending=true;try{if(await myMute())return toast('🔇 You are muted');const badge=ownerAdmin()?'OWNER':isAdmin()?'TEMP ADMIN':'';await api('needoh_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify([{author:playerName(),author_key:pkey(),badge,message_date:new Date().toISOString().slice(0,10),body:text}])});lastSend=Date.now();toast('💬 Message sent');showMessages()}catch(e){toast('Could not send message')}finally{sending=false}};
  async function deleteMessageOnline(id){try{await api(`needoh_messages?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});toast('🗑️ Message deleted');showMessages()}catch(e){toast('Could not delete message')}}
  async function mutePlayer(key,name,minutes){if(!ownerAdmin())return toast('Only Attila can mute players');const until=new Date(Date.now()+minutes*60000);try{await api('needoh_chat_mutes?on_conflict=target_key',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify([{target_key:key,target_name:name||key,muted_until:until.toISOString(),reason:'Muted by Attila',created_by:'Attila',updated_at:new Date().toISOString()}])});toast(`🔇 ${name||key} muted for ${minutes}m`);showMessages()}catch(e){toast('Could not mute player')}}
  async function syncDashboardFields(){if(playerName()==='Player')return;try{await api(`needoh_players?player_key=eq.${encodeURIComponent(pkey())}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({world:Math.max(1,Math.min(5,Number(state.world)||1)),selected_squishy:state.selected||'Common',boxes_opened:Math.floor(Number(state.boxesOpened)||0),bosses_defeated:Math.floor(Number(state.bossesDefeated)||0),updated_at:new Date().toISOString()})})}catch(e){}}
  async function systemChat(){const text=String($('systemChatText')?.value||'').trim().slice(0,300);if(!text)return toast('Type a system message');try{await api('needoh_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify([{author:'SYSTEM',author_key:'system',badge:'OWNER',message_date:new Date().toISOString().slice(0,10),body:text}])});toast('📢 System chat sent');$('systemChatText').value=''}catch(e){toast('Could not send system chat')}}
  const previousShowAdmin=showAdmin;
  showAdmin=async function(){
    await previousShowAdmin();if(!isAdmin())return;const host=$('hubContent');if(!host||document.getElementById('liveControlCenter'))return;
    try{
      const [players,seasonRows]=await Promise.all([api('needoh_players?select=player_key,display_name,coins,world,selected_squishy,boxes_opened,bosses_defeated,updated_at&order=updated_at.desc&limit=200'),api(`needoh_season_scores?select=player_key,player_name,score&season_key=eq.${encodeURIComponent((()=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return `season-${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`})())}&order=score.desc&limit=3`)]);
      const online=(players||[]).filter(p=>Date.now()-Date.parse(p.updated_at)<60000),ev=window.__needohEvents;
      const card=document.createElement('div');card.id='liveControlCenter';card.className='card control-center';card.innerHTML=`<h2 style="margin-top:0">👑 Live Control Center</h2><div class="control-kpis"><div class="control-kpi"><span class="small">Online</span><b>${online.length}</b></div><div class="control-kpi"><span class="small">Players</span><b>${(players||[]).length}</b></div><div class="control-kpi"><span class="small">Season #1</span><b>${escapeHtml(seasonRows?.[0]?.player_name||'—')}</b></div><div class="control-kpi"><span class="small">Your World</span><b>${state.world}</b></div></div><div class="card"><h3>🔥 Global Event Controls</h3><div class="grid2"><select class="field" id="adminEventType"><option value="luck_rush">🍀 Luck Rush</option><option value="boss_damage">⚔️ Boss Damage</option><option value="box_frenzy">🎁 Box Frenzy</option><option value="secret_rush">✨ Secret Squishy Rush</option></select><input class="field" id="adminEventMult" type="number" min="2" value="5"></div><input class="field" id="adminEventMinutes" type="number" min="1" max="30" value="5"><button class="btn gold" id="adminStartEvent">🔥 START GLOBAL EVENT</button></div>${ownerAdmin()?`<div class="card" style="margin-top:10px"><h3>📢 System Chat</h3><textarea class="field" id="systemChatText" maxlength="300" placeholder="Message shown in global chat"></textarea><button class="btn admin" id="systemChatBtn">SEND SYSTEM CHAT</button></div>`:''}<div class="card" style="margin-top:10px"><h3>👥 Online Players</h3>${online.slice(0,15).map(p=>`<div class="card-row" style="margin-top:7px"><div><b>${escapeHtml(p.display_name)}</b><div class="small">World ${p.world} · ${escapeHtml(p.selected_squishy||'Unknown')} · 📦 ${p.boxes_opened||0} · 👹 ${p.bosses_defeated||0}</div></div><span class="reward">🪙 ${fmt(Number(p.coins)||0)}</span></div>`).join('')||'<div class="small">No players online right now.</div>'}</div>`;
      host.prepend(card);
      $('adminStartEvent').onclick=async()=>{try{await ev.start($('adminEventType').value,Number($('adminEventMult').value)||5,Number($('adminEventMinutes').value)||5);toast('🔥 Global event started');showAdmin()}catch(e){toast('Could not start event')}};
      if($('systemChatBtn'))$('systemChatBtn').onclick=systemChat;
      const unlock=()=>{state.world2Unlocked=state.world3Unlocked=state.world4Unlocked=state.world5Unlocked=true;save(true);render();toast('🛡️ All worlds unlocked')};
      if($('adminWorlds'))$('adminWorlds').onclick=unlock;if($('selfWorlds'))$('selfWorlds').onclick=unlock;
    }catch(e){console.warn('Control center failed',e)}
  };
  $('messagesBtn').textContent='💬 Global Chat';$('messagesBtn').onclick=showMessages;$('adminBtn').onclick=showAdmin;
  styles();syncDashboardFields();setInterval(syncDashboardFields,3500);window.__needohSocialAdminLoaded=true;
})();